Add non UTF-8 text support for `url encode`/`url decode` (#18314)
## Description

- I wanted to see if I could write a helper command in nu for handling
"Content-Disposition" headers as described in #18292
- Researched how it should be
[parsed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Disposition#syntax)
- Realize it's not as straightforward as one might expect: [RFC 5987,
section-3.2.2](https://datatracker.ietf.org/doc/html/rfc5987#section-3.2.2)
  - `filename="easy peasy.txt"`
  - `filename*=iso-8859-1'en'%A3%20rates.txt` (not so easy :pensive:)
- Try
  ```nushell
  '%A3%20rates' | url decode  # | decode iso-8859-1
  ```
  And fail
  ```
   Error: nu::shell::error
  
    × Failed to decode string
     ╭─[repl_entry #1:1:1]
   1 │ '%A3%20rates' | url decode  # | decode iso-8859-1
     · ──────┬──────
     ·       ╰── invalid utf-8 sequence of 1 bytes from index 0
     ╰────
  ```
- Rejoice :tada:
  ```nushell
  '%A3%20rates' | url decode --binary | decode iso-8859-1
  # => £ rates
  ```

## User-facing changes (Release notes)

- `url encode` can now encode binary input too, adding support for
encoding non UTF-8 texts
  ```nushell
  '£ rates' | encode iso-8859-1 | url encode
  # => %A3%20rates
  ```
- `url decode` can now decode inputs that do not evaluate to UTF-8 texts
by returning a binary value (only with the `--binary` switch)
  ```nushell
  '%A3%20rates' | url decode --binary | decode iso-8859-1
  # => £ rates
  ```