use `str join` on binary example outputs
This commits mitigates the following error when the output of an
example is binary data:
```
>_ help commands bytes add
...

Examples:
  Add bytes `0x[AA]` to `0x[1F FF AA AA]`
  > 0x[1F FF AA AA] | bytes add 0x[AA]
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
     ╭─[std.nu:909:1]
 909 │             if not ($example.result | is-empty) {
 910 │                 for line in ($example.result | table | lines) { print $"  ($line)" }
     ·                                                ──┬──   ──┬──
     ·                                                  │       ╰── only string input data is supported
     ·                                                  ╰── input type: binary
 911 │             }
     ╰────
```
which was even hidden by `help`.