Fix `std help externs` (#16590)
## Motivation

* `is_extern` column was removed in nushell/nushell#12832
* `module_name` appears to have been nushell/nushell#10023

It was throwing the following error:

```console
❯ use std/help
❯ help externs 
Error: nu::shell::column_not_found

  × Cannot find column 'is_extern'
     ╭─[std/help/mod.nu:400:17]
 399 │         scope commands
 400 │         | where is_extern == true
     ·                 ────┬────┬
     ·                     │    ╰── value originates here
     ·                     ╰── cannot find column 'is_extern'
 401 │         | select name module_name description
     ╰────
```

## Release notes summary - What our users need to know

Fixes an issue in `std help externs` - it was using a column that is no
longer present.