fix: closure's input type shouldn't be inherited from scope (#18540)
### Closure's input type is not inherited from the surrounding scope

With last release, pipeline input type and how it affects various
expressions are being tracked in a lot more cases.

In fact, at least one too many:
```nushell
def mk-add-suffix [suffix: string]: nothing -> closure {
	{|| $in ++ $suffix }
}
```
```
Error: nu::parser::operator_unsupported_type

  × The '++' operator does not work on values of type 'nothing'.
   ╭─[repl_entry #1:2:6]
 1 │ def mk-add-suffix [suffix: string]: nothing -> closure {
 2 │     {|| $in ++ $suffix }
   ·         ─┬─ ─┬
   ·          │   ╰── does not support 'nothing'
   ·          ╰── nothing
 3 │ }
   ╰────
```

This is now fixed, and closures' input type will be inferred as `any`,
the way it was before `0.114.0`.