feat(error make)!: raise errors for invalid labels (#18755)
- closes #4460

## Description

Not providing spans for error labels fell back to using the *error label
record*'s own span instead. This lead to confusing outcomes, especially
because the error label's structure changed at some point:

|      |                                                            |
| -    | -                                                          |
| from | `record<text: string, start: int, end: int>`               |
| to   | `record<text: string, span: record<start: int, end: int>>` |

## User-facing changes (Release notes)

### Errors for... `error make`?

Not specifying the span for error labels (or not doing so correctly)
confusingly fell back to using the record's own span instead:

```nushell
let var = 2
let span = (metadata $var).span

error make {
	msg: "my error"
	label: { text: "two" }
}
```
```
Error: nu::shell::error

  × my error
   ╭─[repl_entry #1:6:9]
 5 │     msg: "my error"
 6 │     label: {text: "two"}
   ·            ──────┬──────
   ·                  ╰── two
 7 │ }
   ╰────
```

So `error make` succeeded instead of throwing an error. Well, it *did*
throw an error, the one user was trying to, not the one it should due to
`error make` receiving an invalid argument.

From now on `error make` will raise an error of its own when receiving
an invalid argument.

```nushell
let var = 2
let span = (metadata $var).span

error make {
	msg: "my error"
	label: { text: "two" }
}
```
```
Error: nu::shell::missing_required_columns

  × Value is missing required columns.
   ╭─[repl_entry #1:6:9]
 4 │ error make {
 5 │     msg: "my error"
 6 │     label: { text: "two" }
   ·            ───────┬───────
   ·                   ╰── missing `span: record<start: int, end: int>` column
 7 │ }
   ╰────
```