make `pipefail` works with `let` (#16879)
This pr address comment by @132ikl :
https://github.com/nushell/nushell/issues/16760#issuecomment-3344409581

After visiting IR of `let x = ^false | into int`:
```
# 2 registers, 8 instructions, 5 bytes of data
   0: load-literal           %1, glob-pattern("false", no_expand = false)
   1: push-positional        %1
   2: redirect-out           pipe
   3: call                   decl 142 "run-external", %0
   4: redirect-out           value
   5: call                   decl 299 "into int", %0
   6: store-variable         var 320, %0 # let
   7: return                 %0
```
Nushell runs `store-variable` instruction, which collect values from
registry through `collect_reg`. This pr adds `check_exit_status_future`
logic inside `collect_reg` to make pipefail works with `let`.

## Release notes summary - What our users need to know
### pipefail works well with `let`
```
let x = bash -c "echo 123; exit 1" | into int; $x
Error: nu::shell::non_zero_exit_code

  × External command had a non-zero exit code
   ╭─[entry #28:1:9]
 1 │ let x = bash -c "echo 123; exit 1" | into int; $x
   ·         ──┬─
   ·           ╰── exited with code 1
   ╰────
```