Add `short` error_style (#17097)
This PR implements `ShortReportHandler` and the associated
`ErrorStyle::Short`, allowing users to display shorter errors and save
screen space, as mentioned in the related discussion (#16496).

@cptpiepmatz 

## Release notes summary - What our users need to know
Add a new `short` option for `$env.config.error_style` that displays
errors as concise, single-line messages similar to classic shells.

```
$ ll
Error: External command failed: Command `ll` not found (Did you mean `all`?)
```

## Tasks after submitting
N/A