feat: make `Span`'s `Debug` impl succinct (#17782)
I think `Span`'s `Debug` text takes up much more space than needed and
makes `Debug` text of anything containing `Span`s look extremely
verbose.

This PR provides a one line format that also special-cases
`Span::test()` and `Span::unknown()`.

<table width="100%">
<tbody>
<tr>
<td width="500">

### Before

</td>
<td width="500">

### After

</td>
</tr>
<tr>
<td>

```
Span {
	start: 1024,
	end: 1036,
}
```

</td>
<td>

```
Span[1024..1036]
                        

```

</td>
</tr>
<tr>
<td>

```
Span {
	start: 9223372036854775807,
	end: 9223372036854775807,
}
```

</td>
<td>

```
Span(TEST)


```

</td>
</tr>
<tr>
<td>

```
Span {
	start: 0,
	end: 0,
}
```

</td>
<td>

```
Span(UNKNOWN)


```

</td>
</tr>
</tbody>
</table>

As part of a larger error:

```
Error: TestError {
    location: tests/const_/mod.rs:36:22,
    kind: UnexpectedValue {
        expected: Int {
            val: 42,
            internal_span: Span {
            	start: 9223372036854775807,
            	end: 9223372036854775807,
            },
        },
        got: Int {
            val: 10,
            internal_span: Span {
            	start: 130819,
            	end: 130821,
            },
        },
    },
}
```

```
Error: TestError {
    location: tests/const_/mod.rs:36:22,
    kind: UnexpectedValue {
        expected: Int {
            val: 42,
            internal_span: Span(TEST),
        },
        got: Int {
            val: 10,
            internal_span: Span[130819..130821],
        },
    },
}
```

## Release notes summary - What our users need to know
N/A

## Tasks after submitting
N/A