fix(try): only pop error handler if it was pushed by current `try` block (#18519)
This PR makes it so that `try` blocks only pop an error handler if they
actually installed one.

A recent PR (#18173) made `try` blocks insert a `PopErrorHandler`
instruction unconditionally. However, a `try/finally` with no `catch`
_doesn't_ install an error handler, but after that change it still pops
one. Thus, a `try/finally` nested inside another `try` or `try/catch`
will pop the enclosing `try` block's error handler, leading to confusing
(and pretty obviously incorrect) behavior.

Consider the following code:

```nushell
# /path/to/file.nu
try {
    try { print "inner" } finally { print "finally" }
    error make { msg: "error" }
}
print "outer"
```

Current output:

```nushell
> nu /path/to/file.nu
inner
finally
Error: nu::shell::error

  × error
   ╭─[/path/to/file.nu:3:16]
 2 │     try { print "inner" } finally { print "finally" }
 3 │     error make { msg: "error" }
   ·                ────────────────
 4 │ }
   ╰────
```

Note that the error was surfaced despite being thrown inside a `try`
block!

Output after this PR:

```nushell
> nu /path/to/file.nu
inner
finally
outer
```