move assets for `to html`
this solves the following error
```
error: proc-macro derive panicked
  --> crates/nu-cmd-extra/src/extra/formats/to/html.rs:79:10
   |
79 | #[derive(RustEmbed)]
   |          ^^^^^^^^^
   |
   = help: message: #[derive(RustEmbed)] folder '/home/amtoine/.local/share/git/store/github.com/amtoine/nushell/crates/nu-cmd-extra/assets/' does not exist. cwd: '/home/amtoine/.local/share/git/store/github.com/amtoine/nushell'

error[E0599]: no function or associated item named `get` found for struct `Assets` in the current scope
   --> crates/nu-cmd-extra/src/extra/formats/to/html.rs:228:19
    |
81  | struct Assets;
    | ------------- function or associated item `get` not found for this struct
...
228 |     match Assets::get(json_name) {
    |                   ^^^ function or associated item not found in `Assets`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `get`, perhaps you need to implement one of them:
            candidate #1: `SliceIndex`
            candidate #2: `RustEmbed`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `nu-cmd-extra` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```