Bump csv from 1.1.6 to 1.2.0 (#8235)
Bumps [csv](https://github.com/BurntSushi/rust-csv) from 1.1.6 to 1.2.0.
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/fa01b78533a58d6c1087990a79a42c97c6edd069"><code>fa01b78</code></a>
1.2.0</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/2ba20b55d91688d5e0e86b204d9fc2990c7e6df9"><code>2ba20b5</code></a>
readme: various updates</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/521294f87b3e1e286829f85a34f397e007f081ed"><code>521294f</code></a>
msrv: set rust-version = 1.60</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/31c8ebc49d6134f666a6607783883e50460ed87d"><code>31c8ebc</code></a>
readme: updates and set rust-version</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/a0e83883e2f862103edf42b130639cba50fb02f3"><code>a0e8388</code></a>
deps: drop 'bstr'</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/9e1126a3f42574cafd31b2309ce686b66444e865"><code>9e1126a</code></a>
cargo: update some fields</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/d7a4f7dcc6d7d2395a194595f1fd1803fcc9d809"><code>d7a4f7d</code></a>
rust: move to 2021 edition</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/022ac05205e2a525711481e77cf8d6df2c254833"><code>022ac05</code></a>
error: drop 'source' impl</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/9ab83111a7ec047d6542dbd23d305cb1bf0a23ef"><code>9ab8311</code></a>
*: better import grouping and short hand struct init</li>
<li><a
href="https://github.com/BurntSushi/rust-csv/commit/ea0273c531b7f09fabefd6bea68c7a99d42554de"><code>ea0273c</code></a>
*: fix all warnings and update code</li>
<li>Additional commits viewable in <a
href="https://github.com/BurntSushi/rust-csv/compare/1.1.6...1.2.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=csv&package-manager=cargo&previous-version=1.1.6&new-version=1.2.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>