fix(engine, type-system)!: enforce assignment type annotations at runtime (#16079)
# Description
currently the example below results in a type mismatch when
  assigning `$table2` to the value of `$table1`:
```nushell
let table1: table<a: string> = [{a: "foo"}]
let table2: table<b: string> = $table1
```

```io
Error: nu::parser::type_mismatch

  × Type mismatch.
   ╭─[example1.nu:2:32]
 1 │ let table1: table<a: string> = [{a: "foo"}]
 2 │ let table2: table<b: string> = $table1
   ·                                ───┬───
   ·                                   ╰── expected table<b: string>, found table<a: string>
   ╰────
```



However fields populated from the `any` type do not follow such
constraints:

```nushell
let table1: table  = ({a: 1} | into record | to nuon | from nuon);
let table2: table<b: string> = $table1
# * circkets *
```

...and leads to some unexpected results:

```
$ let x: table<a: int> = ({a: 1} | to nuon | from nuon); $x | describe
record<a: int>
```

This change/fix now correctly handles the runtime issue with a
`cant_convert` error:

```io
Error: nu::shell::cant_convert

  × Can't convert to table<b: string>.
   ╭─[test2.nu:2:32]
 1 │ let table1: table = ({a: 1} | into record | to nuon | from nuon);
 2 │ let table2: table<b: string> = $table1
   ·                                ───┬───
   ·                                   ╰── can't convert table<a: int> to table<b: string>
   ╰────
```

# User-Facing Changes

This is a breaking change for scripts where `any` coercion/conversions
previously ignored field constraints for records and tables

# Tests + Formatting

https://github.com/nushell/nushell/blob/d80eee5332fff847af033c3263e5945c9bab0b30/tests/repl/test_parser.rs##L817-L833

# After Submitting
<!-- If your PR had any user-facing changes, update [the
documentation](https://github.com/nushell/nushell.github.io) after the
PR is merged, if necessary. This will help us keep the docs up to date.
-->

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Piepmatz <git+github@cptpiepmatz.de>
Co-authored-by: Bahex <Bahex@users.noreply.github.com>
Co-authored-by: Bahex <17417311+Bahex@users.noreply.github.com>