refactor(nu-command/testing): Refactored most nested command integraiont tests in `nu-command` (#17767)
<!--
Thank you for improving Nushell!
Please, read our contributing guide:
https://github.com/nushell/nushell/blob/main/CONTRIBUTING.md
-->
This PR refactored more modules of the `nu-command` command integration
testing suite with the new in-process testing setup. This include:
- `assignment`
- `bytes`
- `conversions`
- `date`
- `hash_`
- `move_`
- `platform`
- `skip`
- `str_`
- `take`
- `url`

I also fixed some things about testing in general. Tests that use the
kitest-based test harness are now detected by rust-analyzer and may be
executed with it.

Tests that require the `nu` binary for execution can now call
`test().add_nu_to_path()`.

Tests that return a `TestError` will now show the location of that error
making debugging the tests a lot easier.
```
failures:

---- commands::url::join::url_join_simple stdout ----
Error: TestError {
    location: crates/nu-command/tests/commands/url/join.rs:15:22,
    kind: UnexpectedValue {
        expected: String {
            val: "http://localhost lol",
            internal_span: Span {
                start: 9223372036854775807,
                end: 9223372036854775807,
            },
        },
        got: String {
            val: "http://localhost",
            internal_span: Span {
                start: 122626,
                end: 122634,
            },
        },
    },
}


failures:
    commands::url::join::url_join_simple
```
The location here can be clicked from your editor jumping direct to the
failing line

And as a little side addition, I moved the constants from the `char`
command in`nu-command` to `nu-utils` to make them available for other
impls as well.

## Release notes summary - What our users need to know
<!--
This section will be included as part of our release notes. See the
contributing guide for more details.
Please include only details relevant for users here. Motivation and
technical details can be added above or below this section.

You may leave this section blank until your PR is finalized. Ask a core
team member if you need help filling this section.
-->
n/a