Span `ListStream` and use `PipelineMismatch`
To properly use `ShellError::PipelineMismatch` in
`PipelineData::collect_string_strict()`, `ListStream` needs to carry a
`Span` as well. Introduces the `span` field on `ListStream` and adjusts
the respective `.into_pipeline_data(.*)` methods.

Requires changes to many commands.

This change directly improves the `from ...` error messages:

Before:

```
/home/stefan/nushell: {a:1 b:2} | from nuon
Error: nu::shell::type_mismatch (link)

  × Type mismatch
   ╭─[entry #1:1:1]
 1 │ {a:1 b:2} | from nuon
   · ────┬────
   ·     ╰── needs string
   ╰────
```

After:

```
/home/stefan/nushell: {a:1 b:2} | from nuon
Error: nu::shell::pipeline_mismatch (link)

  × Pipeline mismatch.
   ╭─[entry #1:1:1]
 1 │ {a:1 b:2} | from nuon
   · ────┬────   ────┬────
   ·     │           ╰── expected: string
   ·     ╰── value originates from here
   ╰────
```