fix all mentions to the old path to the standard library
Command used
```bash
[.github/**/* **/*.rs **/*.nu]
| each {|target|
    sd 'crates/nu-utils/standard_library' 'crates/standard_library' $target
}
```

i used this complex command because of
```bash
>_ sd 'crates/nu-utils/standard_library' 'crates/standard_library' **/*
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #67:1:1]
 1 │ sd 'crates/nu-utils/standard_library' 'crates/standard_library' **/*
   · ─┬
   ·  ╰── can't run executable
   ╰────
  help: Argument list too long (os error 7)
```