put the `null` keys in quotes in the config
this avoids the following error
```nushell
> {null: "foo"}
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #1:1:1]
 1 │ {null: "foo"}
   ·  ──┬─
   ·    ╰── can't convert nothing to string
   ╰────
```