fix unknown_command when parsing certain strings with equal signs
# Description

Prevents errors when `=` is used in raw strings
or strings inside lists/records:

```
> ["=a"]
Error: nu::parser::unknown_command

  × Unknown command.
   ╭─[entry #9:1:1]
 1 │ ["=a"]
   · ───┬──
   ·    ╰── unknown command
   ╰────
```

```
> r#'=a'#
Error: nu::parser::unknown_command

  × Unknown command.
   ╭─[entry #5:1:1]
 1 │ r#'=a'#
   · ───┬───
   ·    ╰── unknown command
   ╰────
```

# User-Facing Changes

Environment shorthand variable names must satisfy `is_identifier`.