Add all `LabeledError` structure parts to `error make` (#17037)
This allows all of the inputs to a `LabeledError` structure to be
accessed from inside of Nushell scripts, not just plugins, including:
* multiple labels (see error from `1 + ""`)
* errors inside of errors (see error from `']' | from nuon`)
* custom codes instead of only `nu::shell::error`
* URL's added to errors using the `url` key

This is a complete rewrite of the `error make` command using `FromValue`
to simplify the parsing a _lot_. I did have to write a `FromValue`
implementation for `nu_protocol::Span` that goes from a record into a
`Span` object. The error checking happens in there instead of in `error
make` now.

Here are a few examples:

```
> def foo [pond sink] {
    error make {
        msg: "this is fishy"
        code: "my::error"
        label: [
            {text: "fish right here" span: (metadata $pond).span}
            {text: "don't fish here" span: (metadata $sink).span}
        ]
        help: "something to tell the user as help"
        url: "https://nushell.sh"
    }
}
> foo "pond" "sink"
Error: my::error (link)

  × this is fishy
   ╭─[entry #2:1:5]
 1 │ foo "pond" "sink"
   ·     ───┬── ───┬──
   ·        │      ╰── don't fish here
   ·        ╰── fish right here
   ╰────
  help: something to tell the user as help
> try {
    foo pond "not a pond"
} catch {|e|
    error make {
        msg: "An outer error"
        inner: [($e.json | from json)]
    }
}
Error: nu::shell::error

  × An outer error
   ╭─[entry #3:4:5]
 3 │ } catch {|e|
 4 │     error make {
   ·     ─────┬────
   ·          ╰── originates from here
 5 │         msg: "An outer error"
   ╰────

Error: my::error (link)

  × this is fishy
   ╭─[entry #3:2:9]
 1 │ try {
 2 │     foo pond "not a pond"
   ·         ──┬─ ──────┬─────
   ·           │        ╰── don't fish here
   ·           ╰── fish right here
 3 │ } catch {|e|
   ╰────
  help: something to tell the user as help
```

The `(link)` is clickable if the right `$env.config` settings are
enabled, or it will print `https://example.com` to the screen.

<!--
Thank you for improving Nushell!
Please, read our contributing guide:
https://github.com/nushell/nushell/blob/main/CONTRIBUTING.md
-->

## Release notes summary - What our users need to know

* Add the all parts of the `LabeledError` structure to the
`error_struct` argument of `error make`

## Tasks after submitting
<!-- Remove any tasks which aren't relevant for your PR, or add your own
-->
- [ ] Update the
[documentation](https://github.com/nushell/nushell.github.io)